import Image from "next/image";
import { Inter } from "next/font/google";
import Head from "next/head";
import { Button } from "@/components/Button";
import { Input } from "@/components/Input";
import { WaitlistForm } from "@/components/WaitlistForm";
import { Label } from "@/components/ui/label";
import { useEffect, useRef } from "react";
import wordmarkLogo from "@/public/wordmark.png";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <main
        className={`flex min-h-screen text-white flex-col py-12 items-center font-body justify-between px-8 ${inter.className}`}
      >
        <Head>
          <title>Punteer.com</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.png" />
        </Head>
        <div className="max-w-[540px]  bg-black/20 backdrop-blur-sm text-white rounded-sm  w-full px-8 p-12">
          <Image
            src={wordmarkLogo}
            className="w-[100px] md:w-[120px] mx-auto"
            alt="Punteer Logo"
          />
          <h1 className="mb-4 text-3xl font-bold text-center md:text-4xl font-heading">
            Punteer is coming
          </h1>
          <p className="my-4 text-sm text-center text-gray-300">
            Curious about the next big thing in social media? Secure your spot
            on our waitlist and be the first to explore our innovative platform!
          </p>
          <p className="my-4 mb-2 font-semibold text-center text-gray-200">
            <span className="text-green-400">2340</span> PEOPLE WAITING
          </p>
          {/* <WaitlistForm /> */}
          <form className="flex flex-col gap-2 mt-12">
            <div>
              <Label htmlFor="email">Email</Label>
              <Input
                className="rounded-sm bg-white/80"
                id="email"
                type="email"
                placeholder="Email"
              />
            </div>
            <div>
              <Label htmlFor="full-name">Full Name</Label>
              <Input
                className="rounded-sm bg-white/80"
                id="full-name"
                type="text"
                placeholder="Full Name"
              />
            </div>
            <Button variant={"default"} type="button" className="rounded-sm ">
              Join the waitlist
            </Button>

            <div className="p-2 bg-white max-w-[420px] mx-auto w-full"></div>
            <div className="p-2 bg-white max-w-[420px] mx-auto w-full"></div>
          </form>
        </div>
      </main>
      <footer className="flex items-center justify-center p-4 text-sm text-gray-700 bg-gray-100/80">
        <Image src={wordmarkLogo} className="w-[100px]" alt="Punteer Logo" />
        <p>© 2023 Punteer. All rights reserved</p>
      </footer>
    </>
  );
}
